"""Project-wide protocol and BlueZ constants."""

SANLIGHT_COMPANY_ID = 0x0A8B
SANLIGHT_MODEL_ID = 0x0001
PRIMARY_NET_INDEX = 0
PRIMARY_APP_INDEX = 0
TARGET_DEFAULT_TTL = 5

SANLIGHT_SET_MAX_BRIGHTNESS_OPCODE = 0x06
SANLIGHT_SET_MAX_BRIGHTNESS_STATUS_OPCODE = 0x07
SANLIGHT_GET_MAX_BRIGHTNESS_OPCODE = 0x08
SANLIGHT_GET_MAX_BRIGHTNESS_STATUS_OPCODE = 0x09
SANLIGHT_SET_UPTIME_OPCODE = 0x0A
SANLIGHT_SET_UPTIME_STATUS_OPCODE = 0x0B
SANLIGHT_GET_UPTIME_BRIGHTNESS_OPCODE = 0x0C
SANLIGHT_GET_UPTIME_BRIGHTNESS_STATUS_OPCODE = 0x0D
SANLIGHT_GET_DAYLIGHT_CONFIGURATION_OPCODE = 0x03
SANLIGHT_GET_DAYLIGHT_CONFIGURATION_STATUS_OPCODE = 0x04
SANLIGHT_GET_COMBINED_DAYLIGHT_DATA_OPCODE = 0x0E
SANLIGHT_GET_COMBINED_DAYLIGHT_DATA_STATUS_OPCODE = 0x0F
